package funix.tgcp.busydate;

import java.time.LocalDate;
import java.util.List;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;

import funix.tgcp.config.CustomUserDetails;
import funix.tgcp.user.User;
import funix.tgcp.user.UserService;
import funix.tgcp.util.LogHelper;

@RestController
public class BusyDateController {

	private static final LogHelper logger = new LogHelper(BusyDateController.class);

	
	@Autowired
	UserService userService;
	
	@Autowired
	BusyDateRepository busyDateRepository;
	
    //Lấy danh sách ngày nghỉ của guide hiện tại
    @GetMapping("/api/guides/busy-date")
    public List<BusyDate> getBusyDates(@AuthenticationPrincipal CustomUserDetails userDetails) {
    	
    	User guide;
    	
    	if(userDetails == null) {
    		guide = new User();
    		guide.setId((long)5);
    	} else {
    		guide = userDetails.getUser();
    	}
    	
    	logger.info("guide.getId() " + guide.getId());
    	
    	return busyDateRepository.findByGuideId(guide.getId());         
    	
    }
    
    @GetMapping("/api/guides/{id}/busy-date")
    public List<BusyDate> getBusyDatesByGuideId(@PathVariable Long id) {
    	
    	logger.info("id " + id);
    	return busyDateRepository.findByGuideId(id);         
    	
    }
	
	@PostMapping("/api/guides/busy-date")
	public ResponseEntity<?> saveBusyDates(
			@RequestBody List<LocalDate> dates,
			@AuthenticationPrincipal CustomUserDetails userDetails) {
		logger.info("");
		User guide;
		
    	if(userDetails == null) {
    		guide = new User();
    		guide.setId((long)5);
    	} else {
    		guide = userDetails.getUser();
    	}
		
    	
    	logger.info("guide.getId() " + guide.getId());
		
	    for (LocalDate date : dates) {
	        
			if (!busyDateRepository.existsByGuideIdAndDate(guide.getId(), date)) {
	            BusyDate d = new BusyDate();
	            d.setDate(date);
	            d.setGuide(guide);
	            d.setAutoGenerated(false);
	            
	            logger.info("save " + d.toString());
	            busyDateRepository.save(d);
	        }
	    }
	    return ResponseEntity.ok().build();
	}
	
	@PostMapping("/api/guides/busy-date/delete")
	public ResponseEntity<?> deleteUnavailableDates(
			@RequestBody List<LocalDate> dates,
			@AuthenticationPrincipal CustomUserDetails userDetails) {
		User guide;
		
    	if(userDetails == null) {
    		guide = new User();
    		guide.setId((long)5);
    	} else {
    		guide = userDetails.getUser();
    	}

	    List<BusyDate> toDelete = busyDateRepository
	        .findByGuideId(guide.getId())
	        .stream()
	        .filter(d -> !d.isAutoGenerated() && dates.contains(d.getDate()))
	        .toList();
	    
	    logger.info("guide.getId() " + guide.getId());

	    busyDateRepository.deleteAll(toDelete);

	    return ResponseEntity.ok().build();
	}

	
	

}
