package funix.tgcp.booking;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;

import funix.tgcp.busydate.BusyDate;
import funix.tgcp.busydate.BusyDateRepository;
import funix.tgcp.util.LogHelper;

import java.time.LocalDate;
import java.util.Collections;
import java.util.List;
import java.util.Optional;

@Service
public class BookingService {

	private static final LogHelper logger = new LogHelper(BookingService.class);
	
    @Autowired
    private BookingRepository bookingRepository;

    
    @Autowired
	private BusyDateRepository BusyDateRepository;



    // Tạo booking mới
    public Booking createBooking(Booking bookingRequest) {     
    	logger.info("");
    	return bookingRepository.save(bookingRequest);
    }

    // Lấy danh sách bookings của khách hàng
    public ResponseEntity<?> getBookingsByCustomer(Long customerId) {
        List<Booking> bookings = bookingRepository.findByCustomerId(customerId);

        if (bookings.isEmpty()) {
            return ResponseEntity.ok(Collections.emptyList());
        }

        return ResponseEntity.ok(bookings);
    }

    
    // Lấy danh sách bookings của guide
    public ResponseEntity<?> getBookingsByGuide(Long guideId) {
        List<Booking> bookings = bookingRepository.findByGuideId(guideId);

        if (bookings.isEmpty()) {
        	return ResponseEntity.ok(Collections.emptyList());
        }

        return ResponseEntity.ok(bookings);
    }
    
    public ResponseEntity<?> findAll() {
        List<Booking> bookings = bookingRepository.findAll();

        if (bookings.isEmpty()) {
        	return ResponseEntity.ok(Collections.emptyList());
        }

        return ResponseEntity.ok(bookings);
    }



	public void deleteBooking(Long bookingId) {
		Booking booking = bookingRepository.findById(bookingId).orElseThrow();
        bookingRepository.delete(booking);
	}

	public Optional<Booking> findById(Long bookingId) {
		return bookingRepository.findById(bookingId);
	}

	
	public ResponseEntity<?> confirmBooking(Long bookingId) {
		Optional<Booking> bookingOpt = bookingRepository.findById(bookingId);

        if (bookingOpt.isEmpty()) {
            return ResponseEntity.status(404).body("{\"message\": \"Booking not found\", \"bookingId\": " + bookingId + "}");
        }

        Booking booking = bookingOpt.get();
        
        if (booking.getStatus() == BookingStatus.CONFIRMED) {
            return ResponseEntity.status(400).body("{\"message\": \"Booking is already confirmed\", \"bookingId\": " + bookingId + "}");
        }
        
        
        booking.setCanceledReason(null);
		booking.setStatus(BookingStatus.CONFIRMED);
		bookingRepository.save(booking);
		
		
		LocalDate start = booking.getStartDate().toLocalDate();
        LocalDate end = booking.getEndDate().toLocalDate();
        Long guideId = booking.getGuide().getId();

        while (!start.isAfter(end)) {
            boolean exists = BusyDateRepository.existsByGuideIdAndDate(guideId, start);
            if (!exists) {
                BusyDate date = new BusyDate();
                date.setDate(start);
                date.setGuide(booking.getGuide());
                date.setAutoGenerated(true);
                BusyDateRepository.save(date);
            }
            start = start.plusDays(1);
        }

		return ResponseEntity.ok("{\"message\": \"Booking confirmed successfully\", \"bookingId\": " + bookingId + "}");
	}
	 
	public ResponseEntity<?> cancelBooking(Long bookingId, String reason) {
		Optional<Booking> bookingOpt = bookingRepository.findById(bookingId);

        if (bookingOpt.isEmpty()) {
            return ResponseEntity.status(404).body("{\"message\": \"Booking not found\", \"bookingId\": " + bookingId + "}");
        }

        Booking booking = bookingOpt.get();
        
        if (booking.getStatus() == BookingStatus.CANCELED) {
            return ResponseEntity.status(400).body("{\"message\": \"Booking is already canceled\", \"bookingId\": " + bookingId + "}");
        }

//        if (!booking.isCancelable()) { // Điều kiện nếu không thể hủy
//            return ResponseEntity.status(403).body("{\"error\": \"Cancellation not allowed\", \"bookingId\": " + bookingId + "}");
//        }

        logger.info(reason);
        booking.setStatus(BookingStatus.CANCELED);
        booking.setCanceledReason(reason);
        bookingRepository.save(booking);

        return ResponseEntity.ok("{\"message\": \"Booking canceled successfully\", \"bookingId\": " + bookingId + "}");

	}

	
}

